package-lock.json, package.json, src/App.jsx, src/components/Button.jsx, src/components/Navbar.jsx, src/components/ServiceCard.jsx, src/components/ThemeSwitch.jsx, src/index.css, src/sections/CustomerReviews.jsx, src/sections/Footer.jsx, src/sections/Hero.jsx, src/sections/Services.jsx, src/sections/SpecialOffers.jsx, src/sections/Subscribe.jsx, tailwind.config.js
- **I <your name here> have worked for Feature #3**
**I accept the fact that I have followed the guidelines and have not copied the codes from around the internet**
- **My pull request closes Feature #3 **
**Here are the pictures of changes that I have made 🔽**
Notes: I didn't pull, so ignore .github and README, feel free to change and coloring and such. Otherwise feature is fully implemented. 
---
=> dark mode added

src/sections/Hero.jsx
- I [Pritam Kundu](https://github.com/warmachine028) have worked for <issue number>
- My pull request closes #17
---
=> fix: added fixes for #17

src/sections/Hero.jsx
- I [M Hamza Nadeem](https://github.com/mhamzanadeem) have worked for #26
- My pull request closes #26
I changed px-10 to px-3 on line 17 of `Hero.jsx` file
---
=> Remove title Padding from Hero Section  #FIXED

src/components/ThemeSwitch.jsx
- I [Franco](https://github.com/FranDiSilvestro) have worked for #30 
- My pull request closes #30 
---
=> [Fix 🛠️] Added fixes for #30

src/index.css
#40 
- I <[CodeTorso](https://github.com/CodeTorso)> am working for <#39>
#40  Issue to be closed 🛅
I have added a orange themed scrollbar with a black background. It is for both white and black backgrounds of your website.
Since that is what I felt the best for the website.
https://github.com/warmachine028/nike/assets/129188028/1623de73-9e09-4a7b-af8f-40d430e5a8dc
=> modified scrollbar to match website theme.

src/index.css
This PR closes issue number #43 📐
I [CodeTorso](https://github.com/CodeTorso) have worked on #43 
This PR helps me working on another issue #39 
=> disabled users from selecting or dragging images

src/index.css
#39 📐
- I [CodeTorso](https://github.com/CodeTorso) have worked for #39 
#39  Issue to be closed 🛅
- My pull request closes #39 
Before merging this PR please merge #44 for better look of website.
---
=> text selection color changed to match with website theme

src/sections/Subscribe.jsx
I [M Hamza Nadeem](https://github.com/mhamzanadeem) have worked for #31
- My pull request closes #31
I made changes on line 15  of file Subscribe.jsx
---
=> [BUG 🐞] Sign Up Input  # FIXED

src/App.jsx, src/components/Menu.jsx, src/components/Navbar.jsx, src/contexts/MenuContext.tsx
- I Franco (https://github.com/FranDiSilvestro) have worked for #1
---
=> [FEATURE 💡] Hamburger menu (not finished)

src/App.jsx, src/components/Menu.jsx, src/components/Navbar.jsx, src/contexts/MenuContext.tsx, src/main.jsx
- I Franco (https://github.com/FranDiSilvestro) have worked fo #1 
=> Hamburger menu (not finished)

src/sections/Subscribe.jsx
- Made the Input field's appearance  consistent  in both light and dark modes across all screen sizes. 
- Implemented a focus effect on the input field.
- I [Ayushi Choudhary](https://github.com/ayushichoudhary-19) have worked for #49 
- My pull request closes #49
---
=> Fixed inconsistency in appearance of input field.

src/sections/Hero.jsx
- I [Ayushi Choudhary](https://github.com/ayushichoudhary-19) have worked for https://github.com/warmachine028/nike/issues/48 
- My pull request closes #49
=> [ Updated Hero.jsx ] - Added an animated Number Counter for metrics on the landing page. 

README.md, src/App.jsx, src/assets/icons/chevron-up.svg, src/sections/ScrollToTopButton.jsx, src/sections/index.jsx
- I [Ayushi Choudhary](https://github.com/ayushichoudhary-19) have worked for #53 
- My pull request closes #53 
=> [FEATURE 💡] Add a go to top FAB for Nike

src/App.jsx, src/components/Menu.jsx, src/components/Navbar.jsx
With minimum of code change i implemented minimal design but match to design of project with nice UI , also it has smooth transition while toggling show/hidden 
merge second commit / the first one is not finished 
- My pull request closes #56
**DARK MODE**
**LIGHT MODE**
---
=> #56 New sideMenu 

src/assets/icons/hamburger.svg, src/components/Navbar.jsx, src/sections/Hero.jsx
- I [your name here](your github profile link) have worked for #<issue number>
- My pull request closes #<issuenumber>
---
=> #55 header / heading styles fixed

src/sections/PopularProducts.jsx
- I [fauzi](https://github.com/gonsura) have worked for #63
- My pull request closes #63 
---
=> [Fix 🛠️] fixes for issue #63 typo class declaration at sections PopularProducts.jsx

src/components/Navbar.jsx
- I [Ehsan-Yari](https://github.com/Ehsan-Yari) have worked for #66
- My pull request closes #66 
---
=> added search ui

package-lock.json, package.json, src/sections/Subscribe.jsx
- I [Raktim Shrestha](https://github.com/rakimsth) have worked for #72 
- My pull request closes #72 
=> [FEATURE 💡] Add Email validation during newsletter signup

src/components/ProductCard.jsx
- I [Shrikrushna Patil](https://github.com/Patilshrikrushna07) have worked for #87 
- My pull request closes #87
---
=> [FEATURE 💡] Change Product Card Design

src/App.jsx, src/components/Button.jsx, src/components/Navbar.jsx, src/components/ShoeDetails.jsx
- I [Smit](https://github.com/Smit1610) have worked for #90
- My pull request closes #90 
[Screencast from 2023-10-03 20-54-35.webm](https://github.com/warmachine028/nike/assets/142035941/811d9dfd-2a44-4f25-96d2-6636b46dfa0e)
---
=> [FIX 🛠️] Hamburger menu for View Details

src/App.jsx, src/components/Menu.jsx, src/components/ShoeDetails.jsx, src/components/ThemeSwitch.jsx, src/sections/Cart.jsx, src/sections/index.jsx
- I [Raktim Shrestha](https://github.com/rakimsth) have worked for #86
- My pull request closes #86
Corrected Desktop View
Corrected Mobile View
Fixed the Navbar scroll issue on mobile view
=> [FEATURE 💡] Add Minimalistic Cart UI Design #86

src/index.css
- I [Keshav Aneja](https://github.com/Keshav-Aneja) have worked for #95
- My pull request closes #<95>
The last Pull request was causing some issues, resulting in breaks between links in the cart and shoe section. So I resorted to the traditional approach for smooth scrolling. Sorry for the inconvenience caused.
Kindly Review this PR and please approve it.
=> Fixed Smooth Scrolling

src/components/ShoeCard.jsx, src/sections/Hero.jsx
- I [KeshavAneja](https://github.com/Keshav-Aneja) have worked for #103
- My pull request closes #103
=> [FEATURE 💡] Some UI Improvements

src/components/Button.jsx, src/components/Menu.jsx, src/components/Navbar.jsx, src/components/ProductCard.jsx, src/components/ReviewCard.jsx, src/components/ServiceCard.jsx, src/components/ShoeDetails.jsx, src/components/ThemeSwitch.jsx, src/constants/index.js, src/index.css, src/sections/Cart.jsx, src/sections/CustomerReviews.jsx, src/sections/Hero.jsx, src/sections/PopularProducts.jsx, src/sections/SpecialOffers.jsx, src/sections/SuperQuality.jsx, tailwind.config.js
- I [Famozzy](https://github.com/Famozzy) have worked for #105
- My pull request closes #105
---
=> [FEATURE 💡] dark/light theme improvement

src/components/Menu.jsx, src/components/Navbar.jsx, src/index.css
- I [Abdulrehman Javed](https://github.com/abdulrehmanjaved-1) have worked for #101
- My pull request closes #101
---
=> [FIX 🛠️] Shift in Page when select option of Navbar

.husky/_/husky.sh, helpers/useScroll.js, src/App.jsx, src/components/Navbar.jsx
- I [theDevSoham](https://github.com/theDevSoham) have worked for #113 
- My pull request closes #113 
---
=> [FEATURE 💡] Make Navbar floating

src/App.jsx, src/components/Menu.jsx
- I [Akash Bag](https://github.com/akash0708) have worked for #112 
- My pull request closes #112 
---
=> [FEATURE 💡] Menu needs changes

src/App.jsx
- I [Dylan Buchi](https://github.com/dylanbuchi) worked for #119
- My pull request closes #119
---
=> [FIX 🛠️] Scrolling disabled

src/components/ThemeSwitch.jsx
- I  Kritesh Timsina (https://github.com/KriteshTimsina) have worked for #125 
- My pull request closes #125 
https://github.com/warmachine028/nike/assets/103115789/55a1615f-51a5-45de-b2d3-24abda123dc7
---
=> [FIX 🛠️] Dark mode toggle not working for the first time #125

src/App.jsx, src/components/Navbar.jsx, src/components/ThemeSwitch.jsx
- I [MaximilianoCabreraP](https://github.com/maximilianocabrerap) have worked on #136
- My pull request closes #136
---
=> fix show cart button

src/components/ProductCard.jsx, src/sections/Cart.jsx
- I [Irfan Salim](https://github.com/IrfanSalim) have worked for #137 
- My pull request closes #137 
=> [FEATURE 💡] Update Cart items

src/App.jsx, src/components/Menu.jsx, src/sections/Signin.jsx, src/sections/Signup.jsx
- My pull request closes #128 
---
=> [FEATURE 💡] SignIn/SignUp

src/components/Button.jsx
- I [Abdulrehman Javed](https://github.com/abdulrehmanjaved-1) have worked for #124 
- My pull request closes #124
=> [FEATURE 💡] Designing of buttons

src/sections/Cart.jsx
- I [Keshav Vyas](https://github.com/Master-Keshav) have worked for #143 
- My pull request closes #143 
---
=> [FIX 🛠️] Add Spacing for "Your Cart" text 

src/sections/Cart.jsx
- I [leonyangela](https://github.com/leonyangela) have worked for #143 
- My pull request closes #143 
Before:
After:
---
=> [FIX 🛠️] Add Spacing for "Your Cart" text

src/App.jsx, src/components/Navbar.jsx
- I [Abdulrehman Javed](https://github.com/abdulrehmanjaved-1) have worked for #142 
- My pull request closes #142 
---
=> [FIX 🛠️] Navbar not working

src/components/ProductCard.jsx
- I [Ansell Maximilian](https://github.com/AnsellMaximilian) have worked on #160 
- My pull request closes #160 
I have removed the absolute positioning of the cart icon and moved it to be on the same horizontal level of the price. The shopping cart icon is now responsive on small screens.
=> [FIX 🛠️] Cart Button looks ugly

src/components/ReviewCard.jsx, src/index.css, src/sections/CustomerReviews.jsx
- I [Hanzalah Waheed](https://github.com/hanzalahwaheed) have worked for #152
- My pull request closes #152
[Screencast from 2023-10-17 11-02-17.webm](https://github.com/warmachine028/nike/assets/101456741/1b92b733-4297-4de5-b929-d4c77ac9c046)
---
=> [FEATURE 💡] Improve Testimonials

src/components/ReviewCard.jsx
- I [Bikalpa Paudel](https://github.com/Bikalpa-Paudel) have worked for #140
- My pull request closes #140
---
=> [FEATURE 💡] Element Changing Positions 

src/sections/Cart.jsx
- I [Hanzalah Waheed](https://github.com/hanzalahwaheed) have worked for #164
- My pull request closes #164
---
=> [FIX 🛠️] Navbar overlaps Cart in Mobile View

src/App.jsx, src/components/ProductCard.jsx, src/components/SingleProduct.jsx, src/components/SingleProductCard.jsx, src/constants/index.js, src/index.css, src/sections/ProductsPage.jsx
- I [Hanzalah Waheed](https://github.com/hanzalahwaheed) have worked for #133
- My pull request closes #133
[Screencast from 2023-10-20 06-19-42.webm](https://github.com/warmachine028/nike/assets/101456741/50504567-a299-4537-b1ae-0fab667d85c3)
---
=> [FEATURE 💡] Create a Single Product Component and Page #133

package-lock.json, package.json, src/App.jsx, src/components/ProductCard.jsx
- I [Shoaib Akhtar](https://github.com/shoaib-31) have worked for #177
- My pull request closes #177 
[video.webm](https://github.com/warmachine028/nike/assets/103197883/747f1da6-2b68-4aa1-8c14-e2eebfc7462d)
---
=> [FEATURE 💡] Snackbar notifications Added

src/constants/index.js
- I [Nikhil](https://github.com/Nikhilh26) have worked for #190 
- My pull request closes #190 
---
=> [FIX 🛠️] About us link not found in footer

.husky/pre-commit, src/components/ReviewCard.jsx
- I [Piyush](https://github.com/piyush-linux) have worked for #305 
- My pull request closes #305
- Border-radius and padding to Customer review card
- profile border white for Customer review card
---
> If their is any other query plz ask !
=> fix: CustomerReviewCard UI improve

.husky/_/husky.sh, .husky/pre-commit, package-lock.json, src/components/Navbar.jsx
- I [Dhruv Gahoi](https://github.com/DhruvGahoi) have worked for #163 
- My pull request closes #163 
Added a search overlay
=> feat: searchbar functionality for the mobile view
